version: '3.8'

services:
  app:
    build: .
    container_name: stock-manager
    ports:
      - "8000:8000"
    volumes:
      - ./:/var/www
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    image: postgres:15
    container_name: stock-manager-db
    environment:
      POSTGRES_DB: manage_stock_app
      POSTGRES_USER: root
      POSTGRES_PASSWORD: teststockmanager123
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/db_data

volumes:
  db_data: